/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "api-docs": () => import("@/views/api-docs/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "release_apps-detail": () => import("@/views/release/apps-detail/[id].vue"),
  release_apps: () => import("@/views/release/apps/index.vue"),
  release_upload: () => import("@/views/release/upload/index.vue"),
  system_logs: () => import("@/views/system/logs/index.vue"),
  system_menus: () => import("@/views/system/menus/index.vue"),
  system_roles: () => import("@/views/system/roles/index.vue"),
  system_users: () => import("@/views/system/users/index.vue"),
};
