/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'ph:info-bold',
      order: 5
    }
  },
  {
    name: 'api-docs',
    path: '/api-docs',
    component: 'layout.base$view.api-docs',
    meta: {
      title: 'api-docs',
      i18nKey: 'route.api-docs',
      icon: 'ph:code-bold',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'release',
    path: '/release',
    component: 'layout.base',
    meta: {
      title: 'release',
      i18nKey: 'route.release',
      icon: 'ph:android-logo-bold',
      order: 2
    },
    children: [
      {
        name: 'release_apps',
        path: '/release/apps',
        component: 'view.release_apps',
        meta: {
          title: 'release_apps',
          i18nKey: 'route.release_apps',
          icon: 'ph:app-window-bold',
          order: 1
        }
      },
      {
        name: 'release_apps-detail',
        path: '/release/apps-detail/:id',
        component: 'view.release_apps-detail',
        meta: {
          title: 'release_apps-detail',
          i18nKey: 'route.release_apps-detail',
          hideInMenu: true,
          activeMenu: 'release_apps'
        }
      },
      {
        name: 'release_upload',
        path: '/release/upload',
        component: 'view.release_upload',
        meta: {
          title: 'release_upload',
          i18nKey: 'route.release_upload',
          icon: 'ph:upload-simple-bold',
          order: 2
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'ph:gear-six-bold',
      order: 3,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'system_logs',
        path: '/system/logs',
        component: 'view.system_logs',
        meta: {
          title: 'system_logs',
          i18nKey: 'route.system_logs'
        }
      },
      {
        name: 'system_menus',
        path: '/system/menus',
        component: 'view.system_menus',
        meta: {
          title: 'system_menus',
          i18nKey: 'route.system_menus',
          icon: 'ph:tree-structure-bold',
          order: 3
        }
      },
      {
        name: 'system_roles',
        path: '/system/roles',
        component: 'view.system_roles',
        meta: {
          title: 'system_roles',
          i18nKey: 'route.system_roles',
          icon: 'ph:shield-check-bold',
          order: 2
        }
      },
      {
        name: 'system_users',
        path: '/system/users',
        component: 'view.system_users',
        meta: {
          title: 'system_users',
          i18nKey: 'route.system_users',
          icon: 'ph:users-three-bold',
          order: 1
        }
      }
    ]
  }
];
